### ISSUE TITLE
Grooscript 1.3.0 grails plugin not available on Maven

### ISSUE THREAD

**Issue by ulrichenslin** [chiquitinxx/grooscript-grails3-plugin#13]
The documentation points to two grails plugin packages:
compile 'org.grails.plugins:grooscript:1.3.0'
and
compile 'org.grails.plugins:grails-plugin:1.3.0'

org.grails.plugins:grooscript:1.3.0 is not available on Maven, but seems like the correct package name.
org.grails.plugins:grails-plugin:1.3.0 is available on Bintray and Maven, but the name does not indicate 'grooscript' in the name.

Will it work to rename the following:
grails-plugin/build/config.groovy
classNode.putNodeMetaData('projectName', 'grooscript')

and 

grails-plugin/build/resources/main/application.yml
name: 'grooscript'

**Comment by chiquitinxx** [comment]
grails and gradle grooscript plugins are only available in bintray. But aye the name is not correct
compile 'org.grails.plugins:grails-plugin:1.3.0'. Thank you, I'll try to fix it.

**Comment by chiquitinxx** [comment]
Now is ok in bintray: 'org.grails.plugins:grooscript:1.3.0'
