### ISSUE TITLE
Parenthesis needed in function call.

### ISSUE THREAD

**Issue by dilvan1** [chiquitinxx/grooscript-grails3-plugin#4]
The html file below (from [examples](http://grooscript.org/grails3-plugin/)) works fine. But if the line:
`refreshList ([[id: 1, title:'Groovy in Action'], [id: 2, title:'Grails in Action']])`
is changed to
`refreshList [[id: 1, title:'Groovy in Action'], [id: 2, title:'Grails in Action']]`
it stops working (using `org.grails.plugins:grooscript:1.1.0`).

``` html
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main"/>
        <title>Test</title>
        <asset:javascript src="jquery" />
        <asset:javascript src="grooscript-grails" />
    </head>

    <body>
        <div id="list"></div>

        <grooscript:template onLoad="false" functionName="refreshList" itemSelector="#list" >
            ul {
                data.each { book ->
                    li {
                        p 'Id: ' + book.id + ' Name: ' + book.title
                    }
                }
            }
        </grooscript:template>

        <grooscript:code>
            $(document).ready {
                refreshList ([[id: 1, title:'Groovy in Action'], [id: 2, title:'Grails in Action']])
            }
        </grooscript:code>

        <asset:deferredScripts/>
    </body>
</html>
```

**Comment by chiquitinxx** [comment]
Hello, thanks for contributing grooscript :)

This is groovy stuff, in groovy sometimes parenthesis are mandatory. You can do it yourself in a 'groovyConsole', with this code you get a runtime error

``` groovy
def sum = { list ->
    println list
}

sum [[number: 1], [number: 3]]
```

**Comment by dilvan1** [comment]
Hi,

   If that is the case, update your demo code at
http://grooscript.org/grails3-plugin/ and add the parenthesis:

<div id="list"></div>

<grooscript:template onLoad="false" functionName="refreshList"
itemSelector="#list">
    ul {
        data.each { book ->
            li {
                p 'Id: ' + book.id + ' Name: ' + book.title
            }
        }
    }/grooscript:template
grooscript:code
    $(document).ready {
        refreshList _(_[[id: 1, title:'Groovy in Action'], [id: 2,
title:'Grails in Action’]]_)_
    }/grooscript:code

   Another suggestion, in this same page on the first example, show the
full html page. It took me some time to discover that I had to include the
asset tags:

<asset:javascript src="jquery" /><asset:javascript
src="grooscript-grails" />asset:deferredScripts/

##    Cheers,

Dilvan de Abreu Moreira, Ph.D.     dilvan@gmail.com
http://java.icmc.usp.br
Warning: I use a spam filter, some emails sent to me CAN be lost!
