### ISSUE TITLE
Build fails when creating grooscript-grails.js

### ISSUE THREAD

**Issue by tepsl** [chiquitinxx/grooscript-grails3-plugin#7]
In build.gradle:

``` gradle
    new File('grails-app/assets/javascripts/grooscript-grails.js').text = text
```

But the just cloned repository doesn't have grails-app/assets/javascripts directory, so it fails.
My solution is adding next line before it.

```
    new File('grails-app/assets/javascripts/').mkdirs()
```

**Comment by chiquitinxx** [comment]
Please tell me if you wanna make a pull request or prefer I commit that
changes. Thank you.

2015-11-29 8:01 GMT+01:00 tepsl notifications@github.com:

**Comment by tepsl** [comment]
I want you to commit that.
